version: 0.2

env:
  variables:
    CHILD_CONCURRENCY: 1
    GULP_SERIES: true

phases:
  install:
    commands:
      - npm install -g yarn
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"

  pre_build:
    commands:
      - bash -c "$(cat ./build/codebuild-extras.sh)"
      - echo "$CODEBUILD_GIT_BRANCH"
      - echo "$ARTIFACT_NAME"
      - echo "CODE BUILD VERSION $CODEBUILD_GIT_BRANCH"
      - echo "BUILDING VERSION $ARTIFACT_NAME"
      - printenv
      - yarn install
      - (cd build/module-builder && yarn install && yarn build)

  build:
    commands:
      - (cd src/bp/ui-admin && yarn install && yarn build)
      # OSX Build
      - export npm_config_target_platform=darwin
      - yarn run build --mac
      - yarn run package --mac
      - mkdir -p out/binaries/data/storage
      - touch out/binaries/data/storage/.keep
      - mv out out_darwin
      - mkdir -p out
      # Windows Build
      - export npm_config_target_platform=windows
      - yarn run build --win32
      - yarn run package --win32
      - mkdir -p out/binaries/data/storage
      - touch out/binaries/data/storage/.keep
      - mv out out_win32
      - mkdir -p out
      # Linux Build
      - export npm_config_target_platform=linux
      - yarn run build --linux
      - yarn run package --linux
      - mkdir -p out/binaries/data/storage
      - touch out/binaries/data/storage/.keep
      - mv out out_linux

  post_build:
    commands:
      - ls -a
      - ls -a out_darwin
      - ls -a out_win32
      - ls -a out_linux

artifacts:
  files:
    - '**/*'
  base-directory: out_darwin/binaries
  name: botpress-$ARTIFACT_NAME-darwin-x64.zip
  secondary-artifacts:
    linux:
      files:
        - '**/*'
      base-directory: out_linux/binaries
      name: botpress-$ARTIFACT_NAME-linux-x64.zip
    windows:
      files:
        - '**/*'
      base-directory: out_win32/binaries
      name: botpress-$ARTIFACT_NAME-win-x64.zip

  cache:
    paths:
      - node_modules
      - modules/**/node_modules
      - build/module-builder/node_modules
