version: 0.2

env:
  variables:
    CHILD_CONCURRENCY: 1
    GULP_SERIES: true
    npm_config_target_platform: darwin

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn global add fileicon

  pre_build:
    commands:
      - npm_config_target_platform=darwin yarn install
      - (cd build/module-builder && yarn install && yarn build)

  build:
    commands:
      - (cd src/bp/ui-admin && yarn install && yarn build)
      # OSX Build
      - yarn run build --mac
      - yarn run package --mac
      - mkdir out/binaries/data/storage
      - touch out/binaries/data/storage/.keep
      - fileicon set out/binaries/bp icon.png
      - mv out out_darwin

artifacts:
  files:
    - '**/*'
  base-directory: out_darwin/binaries
  name: botpress-$(./source_version.sh)-darwin-x64.zip

cache:
  paths:
    - node_modules
    - modules/**/node_modules
    - build/module-builder/node_modules
