version: 0.2

env:
  variables:
    CHILD_CONCURRENCY: 1

phases:
  install:
    commands:
      - npm install -g yarn

  pre_build:
    commands:
      - npm_config_target_platform=darwin yarn install
      - cd build/module-builder
      - npm_config_target_platform=darwin yarn install
      - yarn build
      - cd ../..

  build:
    commands:
      - yarn run build --mac
      - yarn run package --mac

artifacts:
  files:
    - 'out/binaries/**/*'
  name: binaries

cache:
  paths:
    - node_modules
    - modules/**/node_modules
    - build/module-builder/node_modules
