# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:carbon
      - image: postgres:9.5
        environment:
          - POSTGRES_USER=botpress
          - POSTGRES_DB=test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore channel-web package cache
          keys:
            - channel-web-{{ checksum "modules/channel-web/package.json" }}
      - restore_cache:
          name: Restore nlu package cache
          keys:
            - nlu-{{ checksum "modules/nlu/package.json" }}
      - restore_cache:
          name: Restore hitl package cache
          keys:
            - hitl-{{ checksum "modules/hitl/package.json" }}
      - restore_cache:
          name: Restore botpress package cache
          keys:
            - bp-{{ checksum "package.json" }}

      - run:
          name: Install botpress dependencies
          command: cd ~/repo && NODE_ENV=development yarn
      - run:
          name: Install module builder dependencies and build
          command: cd ~/repo/build/module-builder/ && NODE_ENV=development yarn && yarn build
      - run:
          name: Install channel-web dependencies and build
          command: cd ~/repo/modules/channel-web && NODE_ENV=development yarn && yarn build
      - run:
          name: Install nlu dependencies and build
          command: cd ~/repo/modules/nlu && NODE_ENV=development yarn && yarn build
      - run:
          name: Install hitl dependencies and build
          command: cd ~/repo/modules/hitl && NODE_ENV=development yarn && yarn build

      - save_cache:
          name: Save channel-web package cache
          key: channel-web-{{ checksum "modules/channel-web/package.json" }}
          paths:
            - ~/repo/modules/channel-web/node_modules
      - save_cache:
          name: Save nlu package cache
          key: nlu-{{ checksum "modules/nlu/package.json" }}
          paths:
            - ~/repo/modules/nlu/node_modules
      - save_cache:
          name: Save hitl package cache
          key: hitl-{{ checksum "modules/hitl/package.json" }}
          paths:
            - ~/repo/modules/hitl/node_modules
      - save_cache:
          name: Save botpress package cache
          key: bp-{{ checksum "package.json"}}
          paths:
            - ~/repo

      - run:
          name: Build botpress
          command: cd ~/repo && NODE_ENV=development yarn build
      - run:
          name: Run tests
          command: yarn test
          environment:
            PG_USER: botpress
            PG_DB: test
