# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:carbon
      - image: postgres:9.5
        environment:
          - POSTGRES_USER=botpress
          - POSTGRES_DB=test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-dependencies-core-{{ checksum "packages/core/package.json" }}
            - v1-dependencies-core-

      - restore_cache:
          keys:
            - v1-dependencies-channel-web-{{ checksum "packages/channel-web/package.json" }}
            - v1-dependencies-channel-web-

      - run: sudo npm install -g npm@6
      - run: sudo npm install -g node-pre-gyp
      - run: npm install --only=dev
      - run: cd ~/repo/ && NODE_ENV=development npm install || true # Workaround for pkg chmod of "bin" in launcher
      - run: cd ~/repo/ && NODE_ENV=development npm install # Try again with directories created
      - run: NODE_ENV=development npm run bootstrap

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/repo/packages/node_modules

      - save_cache:
          key: v1-dependencies-core-{{ checksum "packages/core/package.json" }}
          paths:
            - ~/repo/packages/core/node_modules

      - save_cache:
          key: v1-dependencies-channel-web-{{ checksum "packages/channel-web/package.json" }}
          paths:
            - ~/repo/packages/channel-web/node_modules

      - run:
          name: Test that it builds
          command: NODE_ENV=development npm run build

      - run:
          name: Run all tests
          command: npm run test
          environment:
            PG_USER: botpress
            PG_DB: test
