version: 0.2
phases:
  install:
    commands:
      - echo "****** Install Bundle for Jekyll ******"
      - gem install jekyll bundler
  pre_build:
    commands:
      - cd docs/
      - echo "***** Install Dependancy Ruby *****"
      - bundle install
      - echo "***** Npm Install *****"
      - npm install
  build:
    commands:
      - echo "******* Building Jekyll site *******"
      - chmod +x ./source_version.sh
      - export PACKAGE_VERSION=$(./source_version.sh)
      - 'echo "baseurl: /docs/$(PACKAGE_VERSION)" > _config.prod.yml'
      - make build-production
      - echo "******* Uploading to S3 *******"
      - aws s3 sync _site/ s3://botpress-docs/$PACKAGE_VERSION