version: 0.2
phases:
  install:
    commands:
      - echo "****** Install Bundle for Jekyll ******"
      - gem install jekyll bundler
  pre_build:
    commands:
      - cd docs/
      - echo "***** Install Dependancy Ruby *****"
      - bundle install
      - echo "***** Npm Install *****"
      - npm install
  build:
    commands:
      - echo "******* Building Jekyll site *******"
      - echo "baseUrl: \"/docs/10.1\"" > _config.prod.yml
      - echo "ENV VARIABLES"
      - echo "THERE ===>>>> $CODEBUILD_SOURCE_VERSION"
      - make build-production
      - echo "******* Uploading to S3 *******"
#      - aws s3 sync _site/ s3://botpress-docs/docs
